Sun, 10 Dec 2017 16:57:33 views.py[line:34] DEBUG This is debug message
Sun, 10 Dec 2017 16:57:33 views.py[line:35] INFO This is info message
Sun, 10 Dec 2017 16:57:33 views.py[line:36] WARNING This is warning message
Sun, 10 Dec 2017 16:57:35 views.py[line:60] DEBUG JwBraAdd GET
Sun, 10 Dec 2017 16:57:36 views.py[line:60] DEBUG JwBraAdd POST
Sun, 10 Dec 2017 16:57:36 views.py[line:70] DEBUG stock_add_post start
Sun, 10 Dec 2017 16:57:36 views.py[line:74] DEBUG jwcolour_id=4, jwstyle_id=1, jwsize_id=14
Sun, 10 Dec 2017 16:57:36 views.py[line:95] DEBUG stock_add_post end
Sun, 10 Dec 2017 16:57:36 exception.py[line:135] ERROR Internal Server Error: /jwmod2/jwbra_add
Traceback (most recent call last):
  File "D:\Users\xyu007\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Users\xyu007\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Users\xyu007\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python3\yanapp\jwbra\jwmod\views.py", line 97, in jwBraAdd
    return redirect( reverse("views.JwBraList.as_view",args=[]))
  File "D:\Users\xyu007\AppData\Local\Programs\Python\Python36\lib\site-packages\django\urls\base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Users\xyu007\AppData\Local\Programs\Python\Python36\lib\site-packages\django\urls\resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'views.JwBraList.as_view' not found. 'views.JwBraList.as_view' is not a valid view function or pattern name.

github test


branch3?
